name: Build Android APK

on:
  push:
    branches: [ "main", "master" ] # Berjalan otomatis setiap kali ada update di branch main/master
  workflow_dispatch: # Memungkinkan kita menjalankan proses build secara manual

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4

    - name: Set up Java JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Compile & Build APK Debug
      run: gradle :app:assembleDebug

    - name: Upload Ready-to-Install APK
      uses: actions/upload-artifact@v4
      with:
        name: DSP-220-PRO-Debug-APK
        path: app/build/outputs/apk/debug/app-debug.apk

